/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Entidades.Producto;
import java.util.TreeSet;

/**
 *
 * @author emanu
 */
public class Menu extends javax.swing.JFrame {
private TreeSet<Producto> productos=new TreeSet<>();
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMAdmin = new javax.swing.JMenu();
        JMIProd = new javax.swing.JMenuItem();
        JMConsultas = new javax.swing.JMenu();
        JMINombre = new javax.swing.JMenuItem();
        jMIRubro = new javax.swing.JMenuItem();
        JMIPrecio = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 967, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 719, Short.MAX_VALUE)
        );

        jMAdmin.setText("Administracion");

        JMIProd.setText("Productos");
        JMIProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIProdActionPerformed(evt);
            }
        });
        jMAdmin.add(JMIProd);

        jMenuBar1.add(jMAdmin);

        JMConsultas.setText("Consultas");

        JMINombre.setText("Por Nombre");
        JMINombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMINombreActionPerformed(evt);
            }
        });
        JMConsultas.add(JMINombre);

        jMIRubro.setText("Por Rubro");
        jMIRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIRubroActionPerformed(evt);
            }
        });
        JMConsultas.add(jMIRubro);

        JMIPrecio.setText("Por Precio");
        JMIPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIPrecioActionPerformed(evt);
            }
        });
        JMConsultas.add(JMIPrecio);

        jMenuBar1.add(JMConsultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMIProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIProdActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        AdmProducto cpr=new AdmProducto(productos);
        cpr.setVisible(true);
        escritorio.add(cpr);
    }//GEN-LAST:event_JMIProdActionPerformed

    private void JMINombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMINombreActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        ConProducto cpr=new ConProducto(productos);
        cpr.setVisible(true);
        escritorio.add(cpr);
    }//GEN-LAST:event_JMINombreActionPerformed

    private void jMIRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIRubroActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        ConRubro cpr=new ConRubro(productos);
        cpr.setVisible(true);
        escritorio.add(cpr);
    }//GEN-LAST:event_jMIRubroActionPerformed

    private void JMIPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIPrecioActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        ConPrecio cpr=new ConPrecio(productos);
        cpr.setVisible(true);
        escritorio.add(cpr);
    }//GEN-LAST:event_JMIPrecioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMConsultas;
    private javax.swing.JMenuItem JMINombre;
    private javax.swing.JMenuItem JMIPrecio;
    private javax.swing.JMenuItem JMIProd;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMAdmin;
    private javax.swing.JMenuItem jMIRubro;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
